# Generated by Django 2.2.13 on 2021-02-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contenido',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='skill',
            name='contenido',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(choices=[('icon major fa-gem', 'icon major fa-gem'), ('icon solid major fa-lock', 'icon solid major fa-lock'), ('icon solid major fa-code', 'icon solid major fa-code'), ('icon solid major fa-link', 'icon solid major fa-link'), ('icon solid major fa-cog', 'icon solid major fa-cog'), ('icon solid major fa-desktop', 'icon solid major fa-desktop')], max_length=150),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='contenido',
            field=models.CharField(max_length=10000),
        ),
    ]
